# no-op.yml
#
# Purpose:
# This workflow provides a workaround for the "required status checks" feature in GitHub Actions
# when using path-specific conditions in other workflows. Required checks might remain in a "Pending"
# state if the conditions are not met, thus blocking pull requests from being merged.
# This no-op (no operation) workflow provides dummy success statuses for these required jobs when
# the real jobs do not run due to path-specific conditions.
#
# How it works:
# - It defines jobs with the same names as the required jobs in the main workflows.
# - These jobs simply execute a command (`exit 0`) to succeed immediately.
# - When a pull request is created or updated, both this no-op workflow and the main workflows are triggered.
# - If the main workflows' jobs don't run (due to path conditions), these no-op jobs provide successful statuses.
# - If the main workflows' jobs do run and fail, their failure statuses take precedence,
#   ensuring that pull requests are not merged with failing checks.
#
# Usage:
# - Ensure that the job names in this workflow match exactly the names of the corresponding jobs in the main workflows.
# - This workflow should be kept as-is, without path-specific conditions.

name: no-op Checks
on: pull_request

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
#  ------------------------------------
#  DE-COMMENT POST MERGING
#  ------------------------------------
#
#  pre-commit:
#    runs-on: ubuntu-latest
#    steps:
#      - run: exit 0
#  python-lint:
#    runs-on: ubuntu-latest
#    steps:
#      - run: exit 0
#  test-postgres-hive:
#    runs-on: ubuntu-latest
#    steps:
#      - run: exit 0
#  test-postgres-presto:
#    runs-on: ubuntu-latest
#    steps:
#      - run: exit 0
#  unit-tests:
#    runs-on: ubuntu-latest
#    steps:
#      - run: exit 0
#  test-mysql:
#    runs-on: ubuntu-latest
#    steps:
#      - run: exit 0
#  test-postgres:
#    runs-on: ubuntu-latest
#    steps:
#      - run: exit 0
#  test-sqlite:
#    runs-on: ubuntu-latest
#    steps:
#      - run: exit 0
## ------------------------------------------------------
## TO BE DEPRECATED
## These no-ops were used to deprecate/renaming checks
## and can be safely delete if seen on `master`
## ------------------------------------------------------
  pre-commit:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", ""]
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  python-lint:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", ""]
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  test-postgres-hive:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", ""]
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  test-postgres-presto:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", ""]
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  unit-tests:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", ""]
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  test-mysql:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", ""]
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  test-postgres:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", ""]
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  test-sqlite:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", ""]
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
